docker-compose-yaml: docker-compose.yml

project: content-vic
endpoint: api-lagoon-master.lagoon.vicsdp.amazee.io:30454
api: api-lagoon-master.lagoon.vicsdp.amazee.io:80

tasks:
  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
    - run:
        name: Import or backup DB.
        command: |
          if [[ "$LAGOON_GIT_BRANCH" != "production" ]]; then
            if [[ -z "$PERSIST_DB" ]]; then
              ./scripts/drush-download-db.sh
              ./scripts/drupal/import-db.sh
            fi
          else
            ./scripts/drupal/backup.sh
          fi
        service: cli
    - run:
        name: Deploy drupal.
        command: |
          if [[ "$LAGOON_GIT_BRANCH" = "api" ]] || [[ "$LAGOON_GIT_BRANCH" = "api-edge" ]]; then
            ./scripts/drupal/install-new-site.sh
          else
            ./scripts/drupal/deploy.sh
          fi
        service: cli
    - run:
        name: Post deployed URL to JIRA
        command: |
          if [[ "$LAGOON_PR_HEAD_BRANCH" != "production" ]]; then
            . scripts/jira-post-comment.sh $JIRA_ENDPOINT $JIRA_USERNAME $JIRA_PASSWORD $LAGOON_GIT_BRANCH $LAGOON_GIT_BRANCH "$LAGOON_PR_TITLE"
          fi
        service: cli

environments:
  production:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: 'drush cron'
        service: cli
      - name: drush scheduled updates cron
        schedule: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"
        command: 'drush tide-core-scheduled-updates-cron'
        service: cli
      - name: Database Backups
        schedule: "0 1,5,9,13,17,21 * * *"
        command: 'bash /app/scripts/drupal/backup-scheduled.sh /app/docroot vicgovau'
        service: cli
  sandbox:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: 'drush cron'
        service: cli
  api:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: 'drush cron'
        service: cli
    routes:
      - nginx-php:
        - "api.content.vic.gov.au"
  api-edge:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: 'drush cron'
        service: cli
    routes:
      - nginx-php:
        - "api-edge.content.vic.gov.au"
