version: '2'
services:
  cli:
    volumes_from:
      - container:amazeeio-ssh-agent
    environment:
      - LAGOON_ENVIRONMENT_TYPE=local
      - XDEBUG_ENABLE=true
    volumes:
      - .:/app:delegated
  nginx:
    networks:
      - amazeeio-network
    environment:
      - AMAZEEIO_URL=content-vicgovau.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080
    volumes:
      - .:/app:delegated
  php:
    environment:
      - LAGOON_ENVIRONMENT_TYPE=local
      - XDEBUG_ENABLE=true
    volumes:
      - .:/app:delegated
  selenium:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    volumes:
      - ./tests/test_data:/app/tests/test_data:delegated
  mariadb:
    image: singledigital/bay-mariadb:latest
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'local'
    ports:
      - 13306:3306
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'local'
    ports:
      - 19200:9200
networks:
  amazeeio-network:
    external: true
