version: '2'
services:
  cli:
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - .:/app/docroot/sites/default/files
  php:
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'
    volumes:
      - .:/app/docroot/sites/default/files
  nginx:
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'
    volumes:
      - .:/app/docroot/sites/default/files
  selenium:
    build:
      context: .
      dockerfile: Dockerfile.selenium
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch.ci
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'
  mariadb:
    image: singledigital/bay-mariadb:latest
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'ci'