version: 2
jobs:
  build:
    docker:
      - image: 8thom/circle-dpc
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Validate composer config.
          command: composer validate --ansi --strict
      - run:
          name: Pull newest Bay images.
          command: composer bay:pull
      - run:
          name: Start Bay stack.
          command: |
            composer bay:start
            sleep 10 # wait for mariadb to startup
            docker ps -a
      - run:
          name: Setup app.
          command: |
            composer app:site-install
            composer bay:cli -- mkdir -p /app/screenshots
      - run:
          name: Install dev dependencies.
          command: composer bay:cli -- composer install --ansi
      - run:
          name: Lint code.
          command: composer bay:cli -- composer app:cs
      - run:
          name: Run unit tests.
          command: composer bay:cli -- vendor/bin/phpunit
      - run:
          name: Run behat tests.
          command: |
            mkdir -p /tmp/artifacts/behat
            if [ "$CIRCLE_NODE_TOTAL" -gt "1" ] ; then
              composer bay:cli -- vendor/bin/behat --format=progress_fail --colors --profile=p$CIRCLE_NODE_INDEX || composer bay:cli -- vendor/bin/behat --format=progress_fail --colors --profile=p$CIRCLE_NODE_INDEX --rerun
            else
              composer bay:cli -- vendor/bin/behat --format=progress_fail --colors || composer bay:cli -- vendor/bin/behat --format=progress_fail --colors --rerun
            fi
            docker cp $(docker-compose ps -q cli):/app/screenshots /tmp/artifacts/behat
      - store_artifacts:
          path: /tmp/artifacts
